### ISSUE TITLE
1.15.2 Crash with BA+ installed 

### ISSUE THREAD

**Issue by ColdFang** [someaddons/performant_issues#23]
So I get random crashes when using BetterAnimals+ together with Performant. Crash is hard to reproduce. Would it help if I turn down the goalselectorrate in Performants Config? Sorry, not very good in reading logs. 

Log: https://pastebin.com/6rjiJad1
Forge Version: 31.2.41
Performant: 3.11m
BetterAnimals+: 1.15.2 - 10.0.0

**Comment by ColdFang** [comment]
ok its not just BA+
Latest crash with minecraft salmon 
https://pastebin.com/SyN7GaVE

**Comment by someaddons** [comment]
should be fixed in v3.12m

**Comment by itsmeow** [comment]
Hey, I think this might still be an issue. Had a user update to 3.12m and the same crash still occurred. I'm the BAP dev
