### ISSUE TITLE
[Bug]: Error during entity move:

### ISSUE THREAD

**Issue by E-daw** [someaddons/performant_issues#242]
### Describe the bug you're experiencing

Server randomly crashes for seemingly no reason due to "error during entity move"

### Reproducability

Unknown, I suppose it happens when a village is in a loaded chunk near night time and villagers try to sleep, or when players do. Otherwise no clue.

Hosting it on a PC at home 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/E-daw/ee170e534b71fb0a9b40c52fa7d59d35

**Comment by someaddons** [comment]
seems to be a problem with fish's undeads rising parasite entities

**Comment by DigitalWendigo** [comment]
I just had the exact same happen with the same error message.

**Comment by someaddons** [comment]
fixed in v3.98, moved entity push to onthread

**Comment by E-daw** [comment]
Still having this issue on the latest 1.16.5 version. Whenever a player on my server gets near a village it cause the server to crash
