### ISSUE TITLE
[1.15.2] Performant breaks Integrated Dynamics drying basin

### ISSUE THREAD

**Issue by GloriousAlpaca** [someaddons/performant_issues#26]
**Describe the bug**
After making a menril block once, the drying basin continues to produce blocks after a short while.
This happened even after I tried breaking it and placing it again.

**To Reproduce**
    1. Put menril wood in a crusher next to the drying basin.
    2. Crush the wood.
    3. Take the menril block out of the drying basin.

**Expected behavior**
I believe it should not endlessly produce menril blocks for free.

** Mod version **
Performant: 3.11m
Integrated Dynamics: 1.1.18
Minecraft: 1.15.2
Forge: 31.2.43

**Comment by someaddons** [comment]
should be fixed in v3.12m

**Comment by hron84** [comment]
@someaddons It seems like it's still an issue with 1.16: https://github.com/CyclopsMC/IntegratedDynamics/issues/984 Please take a look into this.
