### ISSUE TITLE
[Bug]: Running Performant with Custom NPCs breaks NPCs

### ISSUE THREAD

**Issue by RaidenKoizuma** [someaddons/performant_issues#268]
### Describe the bug you're experiencing

When NPCs are set to aggressive, they are supposed to fight the player and other NPCs who are Allies. But while running Performant, this becomes inconsistent. They will sometimes hit the player then stop doing everything completely, not hit the player at all, give chase but not hit, etc. The NPCs are supposed to continue to chase and attack the player/allies until death. When they die, they're supposed to continue to do so. But they don't.

I've tried adding the customnpc entity, "customnpcs:customnpc" to the exclusions in the config but it didn't change anything. I've also tried disabling the load bearer also to no effect.

### Reproducability

Install CustomNPCs-1.16.5.20220515 with latest Performant.
Place an NPC using NPC wand, right click npc using wand, go to advanced, factions, and click aggressive.
Go into survival mode.
The NPC should attack and give chase. But it may not. You're gonna wanna spawn multiples at a time and see, it's very inconsistent.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/RaidenKoizuma/07320ac287faf41031f4a616ac59f30a

**Comment by someaddons** [comment]
fixed in 4.1

**Comment by celophys** [comment]
Hi sorry for using this page again, but also with the new version this bug still exists.
The npcs not always attack their target, expecially when they dies and respawn or when using the wand to reset them
