### ISSUE TITLE
Immersive Portals Dimension Stacking issue

### ISSUE THREAD

**Issue by DohnJenver** [someaddons/performant_issues#81]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
Hi,

When I use immersive portals' dimension stacking feature, traversing to the dimension below causes me to clip through the floor and ignore collisions with some blocks

https://user-images.githubusercontent.com/52298445/103783409-9990fb80-5030-11eb-868f-ffda7a011100.mp4

**To Reproduce**
1. Install the latest version of Immersive Portals and Performant for Forge 1.16.4
2. Load up a world and set up the Dimension stack feature to have the Overworld on top and the Nether on the bottom
3. Go to Y = 5 in the Overworld and mine down 

**Expected behavior**
With Dimension stacking you can traverse dimensions seamlessly just by mining through the obsidian. Video attached below

https://user-images.githubusercontent.com/52298445/103783480-b1687f80-5030-11eb-88f5-9030b163f8ad.mp4

** Mod version **
Forge 35.1.32
Immersive Portals (for Forge) 0.11-mc1.16.4-forge.jar
Performant 1.16.2-4-3.27m

** Logs **
[2021-01-06-4.log](https://github.com/someaddons/performant_issues/files/5776479/2021-01-06-4.log)

**Comment by someaddons** [comment]
fixed in 3.28

**Comment by DohnJenver** [comment]
Hi, just reopening this issue as it only seems to be partially fixed.

With Performant 3.29m installed, I don't clip through most of the dimension anymore but I do clip through the first 2 blocks when I first traverse from one dimension down to the other.

With Performant installed:

https://user-images.githubusercontent.com/52298445/104091560-08ab6180-5276-11eb-9f8b-7c98edcb0c24.mp4

Without Performant installed (**Expected Behaviour**):

https://user-images.githubusercontent.com/52298445/104091566-11039c80-5276-11eb-8dfc-d912637b987a.mp4

Using the latest version of Forge in both (35.1.36).

Logs: [latest.log](https://github.com/someaddons/performant_issues/files/5790996/latest.log)

Steps to reproduce are exactly the same as the OP.

**Comment by DohnJenver** [comment]
Wasn't sure if I was meant to comment on the original issue or make a new one so apologies for the multiple posts. I don't use GitHub much
