### ISSUE TITLE
<Player> moved wrongly! with the latest update

### ISSUE THREAD

**Issue by tobi1449** [someaddons/performant_issues#82]
**Describe the bug. 1.12 is no longer supported, do not make bugreports for it.**
After the latest update of performant, players regularly get stopped mid-air when jumping and/or sprinting and "<Player> moved wrongly!" is printed in the log file.
Items like the Effortless Ring from Evilcraft or weapons that increase movementspeed make it appear more frequently.

**To Reproduce**
1. Install latest performant update
2. Optional: Equip stuff that makes you faster
2. Sprint and/or Jump

** Mod version **
Performant-1.16.2-4-3.28m
Forge 35.1.28

**Comment by someaddons** [comment]
try if 3.29m fixes it, couldnt reproduce myself

**Comment by tobi1449** [comment]
Unfortunately 3.29m didn't fix it. However disabling the new adaptiveSpeed option for entities seems to be a temporary solution.

**Comment by someaddons** [comment]
should be fixed in 3.30m

**Comment by PantsWP** [comment]
Can confirm, still occurring in 3.30m, especially when moving very fast.

**Comment by someaddons** [comment]
well it is a normal thing when you're moving fast
